In [1]:
index=2

In [2]:
import os
os.chdir('../../')

In [3]:
import pandas as pd
from pathlib import Path
from PIL import Image
import json
import random

In [4]:
root_path = Path('./data/')

In [5]:
style_df = pd.read_csv(root_path / 'metadata' / 'style.csv')
content_df = pd.read_csv(root_path / 'metadata' / 'content.csv')
content_df.shape, style_df.shape

((83, 6), (42, 5))

In [6]:
content_df.shape[0]*style_df.shape[0]*3

10458

In [7]:
elements = content_df.shape[0]//5
print(elements)
content_df = content_df.loc[index*elements:index*elements + elements -1]

16

In [8]:
content_df.head()

,Title,Author,Orientation,Resolution,File_name,Notes
0,Big Campbell Soup Can 19C,Andy Warhol,Portrait,598 × 800,big_campbells_soup_can_19c.jpg,NaN
1,Cats Named Sam IV,Andy Warhol,Portrait,500 × 765,cats_named_sam_iv_61.jpg,NaN
2,Soup Can Tomato,Andy Warhol,Portrait,1596 × 2000,soup_can_tomato.jpg,NaN
3,Virgin Annunciate,Antonello da Messina,Portrait,552x720,annunciate.jpg,NaN
4,Self-Portrait as the Allegory of Painting,Artemisia Gentileschi,Portrait,818x1080,allegorie.jpg,NaN

In [9]:
style_df.head()

,Title,Author,Resolution,File_name,Notes
0,Marilyin Monroe,Andy Warhol,2000 × 1992,marilyn_monroe.jpg,NaN
1,The Liver Is the Cock's Comb,Arshile Gorky,1280x952,the_liver_is_the_cocks_comb.jpg,Luigi
2,Flowers,Ben Giles,512x512,flowers.jpg,NaN
3,Bed of Chrysanthemums,Claude Monet,688x1024,bed_of_chrysanthemums.jpg,Luigi
4,Grainstacks,Claude Monet,1280x1010,grainstacks.jpg,Luigi

In [10]:
content_path = root_path / 'content-images'
style_path = root_path / 'style-images'

metadata_path = root_path / 'output' / 'metadata'
metadata_path.mkdir(exist_ok=True, parents=True)

In [62]:
start = index*elements*style_df.shape[0]*3
print(f'Starting from {start} name')

curr = 0
for i, content in content_df.iterrows():
    for j, style in style_df.iterrows():
        for k, weight in enumerate([2.5e4, 3e4, 3.5e4]):  

            content_img_path = content_path / content['File_name']
            style_img_path = style_path / style['File_name']
            output_name = str(start+curr)
            
            metadata = {
                "description": "TBD",
                "image": "TBD",
                "name" : f"{content['Title']} + {style['Title']}",
                "animation_url": "TBD",
                "attributes": [
                    {
                        "trait_type": "Content",
                        "value": content['Title']
                    },
                    {
                        "trait_type": "Content Author",
                        "value": content['Author']
                    },
                    {
                        "trait_type": "Style",
                        "value": style['Title']
                    },
                    {
                        "trait_type": "Style Author",
                        "value": style['Author']
                    },
                    {
                        "trait_type": "Orientation",
                        "value": content['Orientation']
                    },
                    {
                        "trait_type": "File Name",
                        "value": output_name
                    },
                    {
                        "trait_type": "Style weight",
                        "value": weight
                    }
                ]
            }

            print(f"Processing content image: {content['File_name']}")
            print(f"Processing style: {style['File_name']}")
            print(json.dumps(metadata, indent=4))
            
            #content_img = Image.open(content_img_path)
            #style_img = Image.open(style_img_path)
            #content_img.show()
            #style_img.show()

            !python neural_style_transfer.py --content_img_name {content['File_name']} --style_img_name {style['File_name']} --output_img_name {output_name} --video {"True"} --style_weight {str(weight)}

            file_metadata_path = metadata_path / (output_name + '.json')
            with open(file_metadata_path, 'w') as f:
                json.dump(metadata, f)
            
            curr+=1
            print()
        
        print()
    
    print()

Starting from 10080 name
10080

10081

10082


10083

10084

10085


10086

10087

10088


10089

10090

10091


10092

10093

10094


10095

10096

10097


10098

10099

10100


10101

10102

10103


10104

10105

10106


10107

10108

10109


10110

10111

10112


10113

10114

10115


10116

10117

10118


10119

10120

10121


10122

10123

10124


10125

10126

10127


10128

10129

10130


10131

10132

10133


10134

10135

10136


10137

10138

10139


10140

10141

10142


10143

10144

10145


10146

10147

10148


10149

10150

10151


10152

10153

10154


10155

10156

10157


10158

10159

10160


10161

10162

10163


10164

10165

10166


10167

10168

10169


10170

10171

10172


10173

10174

10175


10176

10177

10178


10179

10180

10181


10182

10183

10184


10185

10186

10187


10188

10189

10190


10191

10192

10193


10194

10195

10196


10197

10198

10199


10200

10201

10202


10203

10204

10205



10206

10207

10208


10209

10210

10211


10212

10213

10214


10215

10216

10217


10218

10219

10220


10221

10222

10223


10224

10225

10226


10227

10228

10229


10230

10231

10232


10233

10234

10235


10236

10237

10238


10239

10240

10241


10242

10243

10244


10245

10246

10247


10248

10249

10250


10251

10252

10253


10254

10255

10256


10257

10258

10259


10260

10261

10262


10263

10264

10265


10266

10267

10268


10269

10270

10271


10272

10273

10274


10275

10276

10277


10278

10279

10280


10281

10282

10283


10284

10285

10286


10287

10288

10289


10290

10291

10292


10293

10294

10295


10296

10297

10298


10299

10300

10301


10302

10303

10304


10305

10306

10307


10308

10309

10310


10311

10312

10313


10314

10315

10316


10317

10318

10319


10320

10321

10322


10323

10324

10325


10326

10327

10328


10329

10330

10331



10332

10333

10334


10335

10336

10337


10338

10339

10340


10341

10342

10343


10344

10345

10346


10347

10348

10349


10350

10351

10352


10353

10354

10355


10356

10357

10358


10359

10360

10361


10362

10363

10364


10365

10366

10367


10368

10369

10370


10371

10372

10373


10374

10375

10376


10377

10378

10379


10380

10381

10382


10383

10384

10385


10386

10387

10388


10389

10390

10391


10392

10393

10394


10395

10396

10397


10398

10399

10400


10401

10402

10403


10404

10405

10406


10407

10408

10409


10410

10411

10412


10413

10414

10415


10416

10417

10418


10419

10420

10421


10422

10423

10424


10425

10426

10427


10428

10429

10430


10431

10432

10433


10434

10435

10436


10437

10438

10439


10440

10441

10442


10443

10444

10445


10446

10447

10448


10449

10450

10451


10452

10453

10454


10455

10456

10457